#!/usr/bin/env bun
/**
 * U-REI セットアップスクリプト
 * 対話的に初期設定を行い、.envファイルを生成します
 */

import { existsSync, writeFileSync, readFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createInterface } from 'readline';
import { randomBytes } from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

// 色付きコンソール出力
const colors = {
	reset: '\x1b[0m',
	bright: '\x1b[1m',
	green: '\x1b[32m',
	yellow: '\x1b[33m',
	blue: '\x1b[34m',
	cyan: '\x1b[36m',
	red: '\x1b[31m'
};

function log(msg, color = 'reset') {
	console.log(`${colors[color]}${msg}${colors.reset}`);
}

function logStep(msg) {
	console.log(`\n${colors.cyan}▶${colors.reset} ${msg}`);
}

function logSuccess(msg) {
	console.log(`${colors.green}✓${colors.reset} ${msg}`);
}

function logWarn(msg) {
	console.log(`${colors.yellow}⚠${colors.reset} ${msg}`);
}

// 対話的入力
const rl = createInterface({
	input: process.stdin,
	output: process.stdout
});

function ask(question, defaultValue = '') {
	const defaultHint = defaultValue ? ` [${defaultValue}]` : '';
	return new Promise((resolve) => {
		rl.question(`${question}${defaultHint}: `, (answer) => {
			resolve(answer.trim() || defaultValue);
		});
	});
}

function askYN(question, defaultYes = true) {
	const hint = defaultYes ? '[Y/n]' : '[y/N]';
	return new Promise((resolve) => {
		rl.question(`${question} ${hint}: `, (answer) => {
			const a = answer.trim().toLowerCase();
			if (a === '') resolve(defaultYes);
			else resolve(a === 'y' || a === 'yes');
		});
	});
}

// AUTH_SECRET生成
function generateAuthSecret() {
	return randomBytes(32).toString('base64');
}

// 既存の.env読み込み
function loadExistingEnv() {
	const envPath = join(projectRoot, '.env');
	if (!existsSync(envPath)) return {};

	const content = readFileSync(envPath, 'utf-8');
	const env = {};
	for (const line of content.split('\n')) {
		if (line.startsWith('#') || !line.includes('=')) continue;
		const [key, ...valueParts] = line.split('=');
		env[key.trim()] = valueParts.join('=').trim();
	}
	return env;
}

// メイン処理
async function main() {
	console.log(`
${colors.bright}${colors.blue}================================${colors.reset}
${colors.bright}   U-REI セットアップウィザード${colors.reset}
${colors.bright}${colors.blue}================================${colors.reset}
`);

	const existing = loadExistingEnv();
	if (Object.keys(existing).length > 0) {
		logWarn('既存の.envファイルが見つかりました。上書きされます。');
		const proceed = await askYN('続行しますか？', true);
		if (!proceed) {
			log('キャンセルしました。', 'yellow');
			rl.close();
			return;
		}
	}

	const config = {};

	// ========== デプロイ設定 ==========
	logStep('デプロイ設定');

	config.DEPLOY_URL = await ask(
		'本番環境のURL (例: https://example.com/u-rei)',
		existing.AUTH_URL?.replace('http://localhost:5678', '') || 'https://yupika.dilettantegames.net/u-rei'
	);

	config.DEV_PORT = await ask(
		'開発サーバーのポート番号',
		'5678'
	);

	// ========== Google OAuth ==========
	logStep('Google OAuth 設定');
	log('Google Cloud Console で OAuth 2.0 クライアントIDを作成してください。', 'cyan');
	log('https://console.cloud.google.com/apis/credentials', 'cyan');
	console.log();

	config.GOOGLE_CLIENT_ID = await ask(
		'Google Client ID',
		existing.GOOGLE_CLIENT_ID || ''
	);

	config.GOOGLE_CLIENT_SECRET = await ask(
		'Google Client Secret',
		existing.GOOGLE_CLIENT_SECRET || ''
	);

	// ========== Auth設定 ==========
	logStep('認証設定');

	if (existing.AUTH_SECRET) {
		const regenerate = await askYN('AUTH_SECRETを再生成しますか？（既存のセッションは無効になります）', false);
		config.AUTH_SECRET = regenerate ? generateAuthSecret() : existing.AUTH_SECRET;
	} else {
		config.AUTH_SECRET = generateAuthSecret();
		logSuccess('AUTH_SECRETを生成しました');
	}

	// ========== 管理者設定 ==========
	logStep('初期管理者設定');
	log('このメールアドレスで初回ログインすると自動的に管理者になります。', 'cyan');
	log('複数指定する場合はカンマ区切りで入力してください。', 'cyan');
	console.log();

	config.ADMIN_EMAILS = await ask(
		'管理者メールアドレス',
		existing.ADMIN_EMAILS || ''
	);

	// ========== ストレージ設定 ==========
	logStep('ストレージ設定');

	const useDefaultStorage = await askYN('デフォルトのローカルストレージを使用しますか？', true);
	if (useDefaultStorage) {
		config.STORAGE_TYPE = 'local';
	} else {
		config.STORAGE_TYPE = await ask('ストレージタイプ (local/s3)', 'local');
		if (config.STORAGE_TYPE === 's3') {
			logWarn('S3ストレージは現在未実装です。');
		}
	}

	// ========== .env生成 ==========
	logStep('.envファイルを生成しています...');

	const envContent = `# ============================================
# U-REI SNS 環境変数設定
# Generated by setup script at ${new Date().toISOString()}
# ============================================

# ============================================
# デプロイ設定
# ============================================

# 本番環境URL
DEPLOY_URL=${config.DEPLOY_URL}

# 開発サーバーポート
DEV_PORT=${config.DEV_PORT}

# ============================================
# Google OAuth 2.0 認証情報
# ============================================
# Google Cloud Console (https://console.cloud.google.com/) で取得
#
# 承認済みの JavaScript 生成元:
#   - http://localhost:${config.DEV_PORT}
#   - ${config.DEPLOY_URL.replace(/\/u-rei$/, '')}
#
# 承認済みのリダイレクトURI:
#   - http://localhost:${config.DEV_PORT}/auth/callback/google
#   - ${config.DEPLOY_URL}/auth/callback/google

GOOGLE_CLIENT_ID=${config.GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${config.GOOGLE_CLIENT_SECRET}

# ============================================
# Auth.js 設定
# ============================================

AUTH_SECRET=${config.AUTH_SECRET}

# 開発環境URL（開発時はこちらを有効に）
AUTH_URL=http://localhost:${config.DEV_PORT}

# 本番環境URL（本番デプロイ時はこちらを有効に）
# AUTH_URL=${config.DEPLOY_URL}

# ============================================
# 初期管理者設定
# ============================================
# このメールアドレスで初回ログインすると自動的にadmin+activeになる
# 複数指定する場合はカンマ区切り

ADMIN_EMAILS=${config.ADMIN_EMAILS}

# ============================================
# ストレージ設定
# ============================================

STORAGE_TYPE=${config.STORAGE_TYPE}

# ローカルストレージパス (デフォルト: ./data/uploads)
# UPLOAD_PATH=./data/uploads

# 最大アップロードサイズ (デフォルト: 10MB)
# MAX_UPLOAD_SIZE=10485760

# ============================================
# データベース設定
# ============================================

# データベースパス (デフォルト: ./data/u-rei.db)
# DATABASE_PATH=./data/u-rei.db
`;

	const envPath = join(projectRoot, '.env');
	writeFileSync(envPath, envContent);
	logSuccess('.envファイルを作成しました');

	// ========== データディレクトリ作成 ==========
	const dataDir = join(projectRoot, 'data');
	const uploadsDir = join(dataDir, 'uploads');
	if (!existsSync(dataDir)) {
		mkdirSync(dataDir, { recursive: true });
		logSuccess('data/ ディレクトリを作成しました');
	}
	if (!existsSync(uploadsDir)) {
		mkdirSync(uploadsDir, { recursive: true });
		logSuccess('data/uploads/ ディレクトリを作成しました');
	}

	// ========== vite.config.ts更新 ==========
	logStep('vite.config.ts を更新しています...');
	const viteConfigPath = join(projectRoot, 'vite.config.ts');
	const viteConfig = `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	server: {
		port: ${config.DEV_PORT},
		strictPort: true
	},
	ssr: {
		external: ['bun:sqlite']
	}
});
`;
	writeFileSync(viteConfigPath, viteConfig);
	logSuccess('vite.config.ts を更新しました');

	// ========== 完了 ==========
	console.log(`
${colors.bright}${colors.green}================================${colors.reset}
${colors.bright}${colors.green}   セットアップ完了！${colors.reset}
${colors.bright}${colors.green}================================${colors.reset}

${colors.cyan}次のステップ:${colors.reset}

1. Google Cloud Console でリダイレクトURIを設定:
   ${colors.yellow}http://localhost:${config.DEV_PORT}/auth/callback/google${colors.reset}
   ${colors.yellow}${config.DEPLOY_URL}/auth/callback/google${colors.reset}

2. 開発サーバーを起動:
   ${colors.green}bun run dev${colors.reset}

3. ブラウザでアクセス:
   ${colors.blue}http://localhost:${config.DEV_PORT}/${colors.reset}

4. ${config.ADMIN_EMAILS ? `${colors.yellow}${config.ADMIN_EMAILS}${colors.reset} でログインすると管理者になります` : '管理者メールアドレスが未設定です。.envのADMIN_EMAILSを設定してください'}
`);

	rl.close();
}

main().catch((err) => {
	console.error('エラー:', err);
	rl.close();
	process.exit(1);
});
